import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Autogenerated from the docs/ folder structure. Order is controlled by
// `sidebar_position` front matter in each page and `_category_.json` in each
// directory. Switch to an explicit list here if the tree outgrows that.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
