import React, {useEffect, useRef, useState} from 'react';
import useBaseUrl from '@docusaurus/useBaseUrl';

import dimensions from './dimensions.json';

// Generated by screencasts/render.sh from the rendered SVGs themselves, so the
// reserved box can never disagree with the file it is reserving space for.
type Name = keyof typeof dimensions;

interface Props {
  /** Base name of the SVG under static/screencasts, without the extension. */
  name: Name;
  alt: string;
}

/**
 * One animated terminal capture, with its box reserved before it loads.
 *
 * The landing page puts these in a `<Tabs lazy>`, so a panel mounts its image
 * the first time its tab is clicked. An `<img>` with no known dimensions is
 * zero-tall until the SVG arrives, which snapped everything below the tabs
 * upward for a frame. The frame element holds the aspect ratio open and shows a
 * spinner in the meantime.
 *
 * Markdown-authored screencasts on other pages need none of this: Docusaurus
 * rewrites their `src` through webpack and emits `width` and `height`, so the
 * browser reserves their space from the attributes.
 */
export default function Screencast({name, alt}: Props): React.ReactElement {
  const [loaded, setLoaded] = useState(false);
  const img = useRef<HTMLImageElement>(null);
  const src = useBaseUrl(`/screencasts/${name}.svg`);
  const [width, height] = dimensions[name];

  // The panel that is open on arrival is server-rendered, so the browser starts
  // its SVG long before React hydrates and usually finishes it first. That
  // `load` fired against markup with no handler on it yet, and the one attached
  // below never hears anything, which left the spinner turning on top of a
  // recording that was already playing. Ask the element directly once, after
  // hydration. Panels opened by a tab click mount later and take the event.
  useEffect(() => {
    if (img.current?.complete) {
      setLoaded(true);
    }
  }, []);

  return (
    <span className="screencast-frame" style={{aspectRatio: `${width} / ${height}`}}>
      {!loaded && (
        <span className="screencast-frame__loading">loading the recording</span>
      )}
      <img
        ref={img}
        className="screencast"
        src={src}
        alt={alt}
        width={width}
        height={height}
        onLoad={() => setLoaded(true)}
        // A capture that fails to load should not leave a spinner running
        // forever; the alt text is the fallback either way.
        onError={() => setLoaded(true)}
      />
    </span>
  );
}
